apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karavan-application.fullname" . }}
  labels:
    {{- include "karavan-application.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 1
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "karavan-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karavan-application.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.karavanapplication.image.repository }}:{{ .Values.karavanapplication.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.karavanapplication.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.karavanapplication.secretenv.enabled }}
          envFrom:
          - secretRef:
              name: {{ include "karavan-application.fullname" . }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: {{ .Values.service.containerPort }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5 
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: {{ .Values.service.containerPort }}
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
